[package]
name = "ripex-fuzz"
version = "0.1.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
ripex = { path = "../.." }

[profile.fuzz]
inherits = "release"
opt-level = 3
debug = 1
overflow-checks = true

[[bin]]
name = "fuzz_all"
path = "fuzz_targets/fuzz_all.rs"
test = false
doc = false

[[bin]]
name = "fuzz_js"
path = "fuzz_targets/fuzz_js.rs"
test = false
doc = false

[[bin]]
name = "fuzz_python"
path = "fuzz_targets/fuzz_python.rs"
test = false
doc = false

[[bin]]
name = "fuzz_go"
path = "fuzz_targets/fuzz_go.rs"
test = false
doc = false
