/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AstSummary {
  kind: string
  topLevelNodes: number
  expressionNodes: number | null
}

export interface Comment {
  kind: CommentKind
  text: string
  span: Span
}

export type CommentKind =  'line'|
'block'|
'hashbang';

export declare function detectLanguage(filename: string): Language | null

export interface Diagnostic {
  code: string
  message: string
  span: Span
}

export interface Facts {
  symbols: Array<ParsedSymbol>
  imports: Array<ParsedImport>
  calls: Array<ParsedCall>
  variables: Array<ParsedVariable>
}

export interface ImportSpecifier {
  imported: string
  local: string
  kind: string
}

export type Language =  'javascript'|
'typescript'|
'python'|
'go'|
'rust'|
'c'|
'cpp'|
'csharp';

export declare function parse(source: string, options?: ParseOptions | undefined | null): Promise<ParseOutput>

export interface ParsedCall {
  kind: string
  calleeText: string
  object: string | null
  line: number
  column: number
  isAwait: boolean
  isOptional: boolean
  typeArgs: Array<TypeKind>
}

export interface ParsedImport {
  kind: string
  source: string
  localName: string | null
  importedName: string | null
  line: number
  isTypeOnly: boolean
  isReexport: boolean
  specifiers: Array<ImportSpecifier>
  isStarImport: boolean
  modulePath: Array<string>
}

export interface ParsedParam {
  name: string
  typeAnnotation: string | null
  defaultValue: string | null
}

export interface ParsedSymbol {
  kind: string
  name: string
  exported: boolean
  visibility: string
  lineStart: number
  lineEnd: number
  signature: string
  isTest: boolean
  isAsync: boolean
  returnType: string | null
  isConstructor: boolean
  isDestructor: boolean
  isVirtual: boolean
  isOverride: boolean
  isAbstract: boolean
  isStatic: boolean
  isConstexpr: boolean
  isFinal: boolean
  storageClass: string
  templateParams: Array<string>
  attributes: Array<string>
  baseClasses: Array<string>
  typeKind: TypeKind
  docString: string | null
  params: Array<ParsedParam>
}

export interface ParsedVariable {
  name: string
  kind: string
  typeAnnotation: string | null
  isMutable: boolean
  lineDef: number
  scopeSymbol: string | null
  scopeStart: number
  scopeEnd: number
  usageSites: Array<UsageSite>
  storageClass: string
  typeKind: TypeKind
  isConstructor: boolean
  isDestructor: boolean
  isImported: boolean
  isStatic: boolean
  isConstexpr: boolean
  isThreadLocal: boolean
  isExtern: boolean
}

export interface ParseOptions {
  language?: string
  filename?: string
  extension?: string
  includeAstSummary?: boolean
}

export interface ParseOutput {
  language: Language
  status: Status
  completeness: boolean
  truncated: boolean
  effectiveMode: string
  diagnostics: Array<Diagnostic>
  comments: Array<Comment>
  astSummary: AstSummary | null
  facts: Facts
}

export declare function parseSync(source: string, options?: ParseOptions | undefined | null): ParseOutput

export interface Pos {
  offset: number
  line: number
  column: number
}

export interface Span {
  start: Pos
  end: Pos
}

export type Status =  'complete'|
'recovered'|
'limit_exceeded'|
'failed';

export declare function supportedLanguages(): Array<Language>

export interface TypeKind {
  kind: string
  name: string | null
  items: Array<TypeKind>
}

export interface UsageSite {
  line: number
  column: number
  usageKind: string
}
